insert into public.catalog_items (line,key,name,kind,sort,active,data) values
  ('botc','mafia','오리지널 마피아','game',1,true,'{"cat":"mafia","lv":"초보","min":6,"max":16,"t":30,"out":true,"host":true}'::jsonb),
  ('botc','secret-hitler','시크릿 히틀러','game',2,true,'{"cat":"mafia","lv":"중급","min":5,"max":10,"t":45,"out":false,"host":false}'::jsonb),
  ('botc','avalon','아발론','game',3,true,'{"cat":"mafia","lv":"중급","min":5,"max":10,"t":30,"out":false,"host":false}'::jsonb),
  ('botc','spyfall2','스파이폴2','game',4,true,'{"cat":"mafia","lv":"초보","min":3,"max":12,"t":20,"out":false,"host":false}'::jsonb),
  ('botc','saboteur','사보타지','game',5,true,'{"cat":"mafia","lv":"초보","min":3,"max":10,"t":30,"out":false,"host":false}'::jsonb),
  ('botc','hitster','힛스터','game',6,true,'{"cat":"party","lv":"초보","min":2,"max":null,"t":30,"out":false,"host":false}'::jsonb),
  ('botc','great-dalmuti','달무티','game',7,true,'{"cat":"party","lv":"초보","min":4,"max":8,"t":15,"out":false,"host":false}'::jsonb),
  ('botc','flip7','플립7','game',8,true,'{"cat":"party","lv":"초보","min":3,"max":18,"t":20,"out":false,"host":false}'::jsonb),
  ('botc','animal-realm','애니멀렐름','game',9,true,'{"cat":"party","lv":"초보","min":3,"max":7,"t":15,"out":false,"host":false}'::jsonb),
  ('botc','cockroach-poker','바퀴벌레포커','game',10,true,'{"cat":"party","lv":"초보","min":3,"max":5,"t":20,"out":false,"host":false}'::jsonb),
  ('botc','zogen','조겐 (Zogen)','game',11,true,'{"cat":"party","lv":"초보","min":2,"max":6,"t":20,"out":false,"host":false}'::jsonb),
  ('botc','kezao','케자오 (Kezao)','game',12,true,'{"cat":"party","lv":"초보","min":2,"max":5,"t":20,"out":false,"host":false}'::jsonb),
  ('botc','partysaurus-20s','파티사우루스20s','game',13,true,'{"cat":"party","lv":"초보","min":3,"max":5,"t":20,"out":false,"host":false}'::jsonb),
  ('botc','five-towers','5타워','game',14,true,'{"cat":"party","lv":"초보","min":2,"max":5,"t":20,"out":false,"host":false}'::jsonb),
  ('botc','goodface-badface','굿페이스밷페이스','game',15,true,'{"cat":"party","lv":"초보","min":2,"max":5,"t":15,"out":false,"host":false}'::jsonb),
  ('botc','word-capture','워드캡처','game',16,true,'{"cat":"party","lv":"초보","min":2,"max":6,"t":10,"out":false,"host":false}'::jsonb),
  ('botc','taco-cat-goat-cheese-pizza','타코캣고트치즈피자','game',17,true,'{"cat":"quick","lv":"초보","min":3,"max":8,"t":10,"out":false,"host":false}'::jsonb),
  ('botc','halli-galli','할리갈리','game',18,true,'{"cat":"quick","lv":"초보","min":2,"max":6,"t":15,"out":false,"host":false}'::jsonb),
  ('botc','ghost-blitz','고스트블리츠','game',19,true,'{"cat":"quick","lv":"초보","min":2,"max":8,"t":20,"out":false,"host":false}'::jsonb),
  ('botc','serpentina','서펜티나','game',20,true,'{"cat":"quick","lv":"초보","min":2,"max":5,"t":15,"out":false,"host":false}'::jsonb),
  ('botc','abraca-what','아브라카왓','game',21,true,'{"cat":"quick","lv":"초보","min":2,"max":5,"t":30,"out":false,"host":false}'::jsonb),
  ('botc','clue','클루','game',22,true,'{"cat":"strategy","lv":"초보","min":2,"max":6,"t":20,"out":false,"host":false}'::jsonb),
  ('botc','code-777','코드777','game',23,true,'{"cat":"strategy","lv":"중급","min":2,"max":5,"t":40,"out":false,"host":false}'::jsonb),
  ('botc','carcassonne','카르카손','game',24,true,'{"cat":"strategy","lv":"중급","min":2,"max":5,"t":35,"out":false,"host":false}'::jsonb),
  ('botc','splendor','스플렌더','game',25,true,'{"cat":"strategy","lv":"중급","min":2,"max":4,"t":30,"out":false,"host":false}'::jsonb),
  ('botc','catan','카탄','game',26,true,'{"cat":"strategy","lv":"중급","min":3,"max":4,"t":60,"out":false,"host":false}'::jsonb),
  ('botc','catan-card','카탄 (카드버전)','game',27,true,'{"cat":"strategy","lv":"중급","min":2,"max":4,"t":30,"out":false,"host":false}'::jsonb),
  ('botc','rummikub','루미큐브','game',28,true,'{"cat":"strategy","lv":"초보","min":2,"max":4,"t":20,"out":false,"host":false}'::jsonb),
  ('botc','harmonies','하모니즈','game',29,true,'{"cat":"strategy","lv":"중급","min":1,"max":4,"t":30,"out":false,"host":false}'::jsonb),
  ('botc','bomb-busters','봄버스터즈','game',30,true,'{"cat":"strategy","lv":"중급","min":2,"max":5,"t":30,"out":false,"host":false}'::jsonb),
  ('botc','sangja-ai','상자아이','game',31,true,'{"cat":"strategy","lv":"중급","min":3,"max":5,"t":40,"out":false,"host":false}'::jsonb),
  ('botc','quoridor','쿼리도','game',32,true,'{"cat":"strategy","lv":"초보","min":2,"max":4,"t":15,"out":false,"host":false}'::jsonb),
  ('botc','chess-mini','체스 (미니)','game',33,true,'{"cat":"strategy","lv":"중급","min":2,"max":2,"t":20,"out":false,"host":false}'::jsonb),
  ('botc','the-gang','더 갱','game',34,true,'{"cat":"coop","lv":"중급","min":3,"max":6,"t":20,"out":false,"host":false}'::jsonb),
  ('botc','the-mind','더마인드','game',35,true,'{"cat":"coop","lv":"초보","min":2,"max":4,"t":20,"out":false,"host":false}'::jsonb),
  ('botc','sageon-jaeguseong','사건의재구성','game',36,true,'{"cat":"coop","lv":"고급","min":1,"max":4,"t":75,"out":false,"host":false}'::jsonb)
on conflict (line,key) do update set name=excluded.name, sort=excluded.sort, data=excluded.data;